apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: odoo-deploy
  name: odoo-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: odoo-deploy
    spec:
      containers:
      - image: odoo:latest
        name: odoo
        resources: {}
status: {}
